{% set name = "cruaktemp" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/cruAKtemp
  git_rev: v{{ version }}

build:
  # number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
  run:
    - netcdf4
    - numpy
    - python-dateutil
    - pyyaml

test:
  requires:
    - nose
    - bmi-tester
  imports:
    - cruAKtemp
  commands:
    - bmi-tester cruAKtemp.bmi_cruAKtemp.BmiCruAKtempMethod

about:
  home: https://csdms.colorado.edu/wiki/Model:CruAKTemp
  license: MIT
  summary: 
    CRUAKTemp provides access to a subsample of CRU NCEP temperature
    data for Alaska.
  dev_url: https://github.com/permamodel/cruAKtemp
