language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/conda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: "nkjZXRb8rBqeMmhNODlMvRgOAv0UaoaJM5PpxH7VUo3ye0xThflQt/Pb7tmeLwOpBecXJpiIc3L7CsLrXot0aK0Qe3RsbsMfutnTZWIcEWKGt3ch7wqMfnrv0hm//1cAV/K5TaFtQwSkmEj3cDB/rJ02k3CsBcIiNt6l21EFCnt4I8uBZhaI2/kq2LLqms6CIoCxZPcw66vxKdZI5Vrx42pVCANsBMna77bsEpKS3ITMPHvUqCA2QgLXGD6BEUb26GbUaaA0vXctLk4yrpuIf1JIWm8FrwXyiQPG/JOXQB7XSR/qNp4/rkdfx5RJDjXTOXLR0kPjUROv52jK/AJAXkgC7ezYlQfXnniu3eirhduQV1a5iQAxdJyNCqTdQPHyR+y7t5y8cEIsUyctv2cqJWb1RRVeNL21ng812+AF25yt+E34vLz/ZfEO/Io+uVIB9ZxfuAz4TNMosV4tPWIIgQaAxVyG17+qK9zhQ37msIeAObH88vXE493p/q6mM/u2rJAsbX+OOyyJxCKZRMPxMqJ76bO1OKHxUEQQopvRsUmd75mC76NlzemlkXDkw+YHanFoyDT+QZnnhLNKpxCHlMGbDi7YVsPEDTpINAhTeFNWrTxzduzDMu0hLcR3Acbffd0f/5mlMh3cUsxUIfAKrIidzxL1iSZ/9h9S+q3Lg3Q="
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
- bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n buildit python=$TRAVIS_PYTHON_VERSION
- source activate buildit
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c defaults -c conda-forge --old-build-string
after_success:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
    echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
  fi
